### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by SirNerdBear** [gregtwallace/apc-p15-tool#10]
The readme details usage, but I don't see how to build/make the tool. I'm not very good at go and I don't see a makefile. 

I have certwarden running in an LXC and was looking to add this for post processing to add certs to my APC UPS. 

Thanks for making this tool, and CertBot. It's been the motivation I needed to stop using a wildcard cert.

**Comment by gregtwallace** [comment]
There is a power shell script in the root of the repo: https://github.com/gregtwallace/apc-p15-tool/blob/main/build.ps1

That said, there isn't really any fuss when building for Go, e.g.,

```
# Windows x64
$env:GOARCH = "amd64"
$env:GOOS = "windows"
$env:CGO_ENABLED = 0
go build -o $outDir/apc-p15-tool-amd64.exe ./cmd/tool
```

Also, unless you have a specific need to build it, the compiled version is posted under Releases:
https://github.com/gregtwallace/apc-p15-tool/releases
