### ISSUE TITLE
Add NMC3 Extra Key Options (4,092 bit RSA & 3x EC Options)

### ISSUE THREAD

**Issue by gregtwallace** [gregtwallace/apc-p15-tool#6]
NMC3 has additional keying options but currently the keys must be generated on device. This PR is to track trying to add additional key support.

4,092 bit RSA should not pose any issues.
EC keys (3x curves) require a different .p15 format and as such implementation may be tricky. In particular, it isn't clear what the APC private key file format looks like exactly since they're generated on device and it doesn't appear they can be extracted from the device.

I modified the pemtrans tool here: https://github.com/freddy36/apc_tools to turn EC pem files into .p15 files and am modeling the implementation attempt based off the result.

**Comment by gregtwallace** [comment]
Hopefully works: https://github.com/gregtwallace/apc-p15-tool/releases/tag/v1.1.0-b1

**Comment by gregtwallace** [comment]
[Aleksey-Maksimov](https://github.com/Aleksey-Maksimov) can you try the new beta with RSA 4,092, and EC Keys of P-256, P-384, and P-521 curves?

I'd like to provide full support of modern keys on NMC3 but I don't have one myself.

**Comment by crytectobi** [comment]
Hi @gregtwallace !
First, thank you for the great effort and tool! Works like a charm regarding RSA.
I tested for you EC P-256 (secp256k1) and RSA 4096 bit with NMC3 firmware
```
su v2.5.0.6
aos v2.5.0.8
boot v1.5.1.1
```
Trying to install the certificate results in the following error:
```
  stderr: 'install: failed to connect to host (ssh: handshake failed: apcssh: server returned wrong fingerprint (b64: <redacted>; hex: <redacted>))'
  stderr_lines: <omitted>
  stdout: |-
    apc-p15-tool v1.1.0-b1
    install: making apc p15 file(s) content from pem
    install: successfully parsed pem files
    install: successfully generated p15 key file content
    install: key type is not supported by NMC2, skipping p15 key+cert file content
    install: apc p15 file(s) data succesfully generated
    apc-p15-tool done
```
With this version both fail the same way. However if I use version 1.0 of your tool with EC, followin error appears:
```
  stderr: 'install: failed to parse pem files (pkcs15: pem key: unsupported pem block type (only pkcs1 and pkcs8 supported))'
  stderr_lines: <omitted>
  stdout: |-
    apc-p15-tool v1.0.0
    install: making apc p15 file from pem
    apc-p15-tool done
```
The UPS website also states PEM or PKCS8, not 15 for private key file:
![image](https://github.com/user-attachments/assets/e9066f94-3ef9-4dca-af36-cb657827ab4e)

Let me know if I can help further in any way.

**Comment by gregtwallace** [comment]
v 1.0.0 does not support EC at all, which is why you're getting the unsupported format error.

For the beta version, the error you receive is not related to the key type. You need to specify the UPS' thumbprint value in order for it to install. Specify the thumbprint value from the error message in the `--fingerprint` option, e.g., `--fingerprint 123abc`.

More generally to EC support, you can check if your firmware is new enough by connecting to your UPS via SSH and typing the `ssl` command. If the command doesn't exist, your firmware is too old. If it does exist, you should be able to use EC keys.

**Comment by gregtwallace** [comment]
Did you actually check the web ui and confirm the certificate was actually the new one?

The tool can’t actually check that. Though now that I’m thinking about it I suppose I could probably look into building some kind of confirmation step where the tool connects to the webui after install.

**Comment by crytectobi** [comment]
Yes I checked the site and exported the certificate:
![image](https://github.com/user-attachments/assets/830b55d1-3da2-4753-9770-5c57c3b5aaca)
P_384 is working as well.
If you chose to integrate a check after the install, please make it optional.
In my opinion it could lead to hiccups, checks could be done with automation, monitoring or manual checks.

**Comment by wallacebrf** [comment]
I would agree to make it optional

**Comment by gregtwallace** [comment]
Awesome! Thank you so much for the feedback. 

As for any check, there isn’t an ‘undo’ install, it would just add a warning message after the fact of the check failed.

**Comment by gregtwallace** [comment]
Completed: https://github.com/gregtwallace/apc-p15-tool/commit/cbb831e0092942d074f7f1b66486a135654b202f
