### ISSUE TITLE
only creates the key file.

### ISSUE THREAD

**Issue by jrbges** [gregtwallace/apc-p15-tool#7]
running this command -> apc-p15-tool.exe create --keyfile ./usnv02idf01-ups01-cert3-key.pem --certfile ./usnv02idf01-ups01-cert3.pem
This is the output
apc-p15-tool v1.1.0
create: making apc p15 file(s) content from pem
create: successfully parsed pem files
create: successfully generated p15 key file content
create: key type is not supported by NMC2, skipping p15 key+cert file content
create: apc p15 file(s) data succesfully generated
create: apc p15 key file apctool.key.p15 written to disk
apc-p15-tool done

Only writes the apctool.key.p15 file to disk. I get no apctool.p15 file.

What format does the .pem input files need to be in?

**Comment by gregtwallace** [comment]
The key you're using appears to be ECDSA or a 4,096 RSA key. These keys aren't supported on NMC2 and as such there is no file generated for the NMC2.

see: https://github.com/gregtwallace/apc-p15-tool#compatibility-notice

**Comment by gregtwallace** [comment]
Modern NMC3 uses the key file that is generated + the cert.pem. If your NMC3 is on an older firmware, you'll need to use an NMC2 compatible key which will cause the file you're looking for to be generated.

**Comment by jrbges** [comment]
Thanks for all your help. I will have to play with it again tomorrow. I have been having a hard time getting our inhouse CA and cert on the web ssl.

Get Outlook for iOS<https://aka.ms/o0ukef>


JamesBishop| 
IT Infrastructure Engineer I
Direct +1 702 263 2764
7000 Lindell Road
NV, 89118
www.ges.com| ***@***.***
CONFIDENTIAL NOTICE: This e-mail transmission (and the attachments, if any, accompanying it) may contain confidential information. The information is intended only for the use of the intended recipient. If you are not the intended recipient, you are hereby notified that any forwarding, disclosure, copying, distribution, or the taking of any action in reliance on the contents of this information is strictly prohibited. Any unauthorized interception of this transmission is illegal under the law. If you have received this transmission in error, please promptly notify the sender by reply e-mail, and then destroy all copies of the transmission.
vGESUS001
________________________________

**Comment by gregtwallace** [comment]
If you want the least headache, I'd recommend use of RSA 2,048 bit keys unless you have a specific requirement that doesn't allow that.
