### ISSUE TITLE
apc-p15-install.exe install: failed to parse pem files (pkcs15: pem key: failed to decode pem block)

### ISSUE THREAD

**Issue by viktormadarasz** [gregtwallace/apc-p15-tool#8]
_Smart-UPS 3000 RM
AP9630JN  ( I dont know what the JN means in the model name could not find online)_

**When I try to use with Letsencrypt certificate (created with Certbot) 
It only creates the apctool.key.p15 bit not the apctool.p15 file 
>> so I could not test further from here**

**However if I use a ZeroSSL Free certificate it creates both files
>> I could go beyond here and try to install the created files .p15 from the Web GUI and also with the apc-p15-install tool**

C:\apc-p15-tool_windows_amd64>

**apc-p15-tool.exe create --keyfile private.pem --certfile cert.pem**

apc-p15-tool v1.1.0
create: making apc p15 file(s) content from pem
create: successfully parsed pem files
create: successfully generated p15 key file content
create: key type is supported by NMC2, generating p15 key+cert file content...
create: apc p15 file(s) data succesfully generated
create: apc p15 key file apctool.key.p15 written to disk
create: apc p15 key+cert file apctool.p15 written to disk
apc-p15-tool done

### However I get error when I try to use the Install tool to deploy the created files to the NMC2 ( same subnet as the host machine)

C:\apc-p15-tool_windows_amd64>

**apc-p15-install.exe --keyfile apctool.key.p15 --certfile apctool.p15 --hostname upsiden.corp.viktormadarasz.com --username apc --password apc --fingerprint 8bff11985ebc0d6ccf47288e452f347414bf32c5**

apc-p15-tool v1.1.0
install: making apc p15 file(s) content from pem
_**install: failed to parse pem files (pkcs15: pem key: failed to decode pem block)**_
apc-p15-tool done

- From the Web UI trying to use the same p15 file neither works.. nothing happens or changes the installed cert ( stays empty on all fields)
- Via SCP while it connects I can not download or upload files it just disconnects when trying to do anything but lists the directory
- Via FTP Same Behaviour as over SCP

I'm lost at this point
Probably I am doing something wrong

![2024-11-20_09-56-16](https://github.com/user-attachments/assets/e060a4e2-2ecf-4a10-97e9-189b3867e74a)

**Comment by gregtwallace** [comment]
create should be used if you want the p15 file(s) for manual use. The install command is expecting the pem files, not p15 files. 

‘--keyfile apctool.key.p15 --certfile apctool.p15’
Should be
‘ --keyfile private.pem --certfile cert.pem’
regardless of if you’re using create or install. 

If you are just trying to install the pem files, skip the create command and just do the install command.

**Comment by viktormadarasz** [comment]
C:\apc-p15-tool_windows_amd64>apc-p15-install.exe --restartwebui --keyfile private.pem --certfile cert.pem --hostname upsiden.corp.viktormadarasz.com --username apc --password apc --fingerprint 95ff846e0c4fdb0763b9604dba616afc6057e3d717d3847aae9c2c687125697a

apc-p15-tool v1.1.0
install: making apc p15 file(s) content from pem
install: successfully parsed pem files
install: successfully generated p15 key file content
install: key type is supported by NMC2, generating p15 key+cert file content...
install: apc p15 file(s) data succesfully generated
install: connected to ups ssh, installing ssl key and cert...
install: apc p15 file installed on upsiden.corp.viktormadarasz.com
install: sending restart command
install: sent webui restart command
install: attempting to verify certificate install...
install: waiting for ups webui restart...
install: web ui leaf cert does not match new cert
apc-p15-tool done



The restartwebui flag made no difference unfortunatelly


can it be a problem with the Cert and Key or in that case I d have been given a  different error??

**Comment by viktormadarasz** [comment]
![image](https://github.com/user-attachments/assets/0d837533-7cb4-4137-a166-19ecee185cea)

Whatever I do it always stick with this self signed cert it has

**Comment by viktormadarasz** [comment]
**Had another go at it .. clean from scratch**

Grabbed the LetsEncrypt Cert.pem and privkey.pem as provided and fed to **apc-p15-install.exe**

`C:\apc-p15-tool_windows_amd64>apc-p15-install.exe --restartwebui --keyfile privkey.pem --certfile cert.pem --hostname upsiden.corp.viktormadarasz.com --username apc --password apc --fingerprint 95ff846e0c4fdb0763b9604dba616afc6057e3d717d3847aae9c2c687125697a
apc-p15-tool v1.1.0
install: making apc p15 file(s) content from pem
install: successfully parsed pem files
install: successfully generated p15 key file content
install: key type is not supported by NMC2, skipping p15 key+cert file content
install: apc p15 file(s) data succesfully generated
install: connected to ups ssh, installing ssl key and cert...
**install: apcssh: ssl cert install: cant install nil data (unsupported key/nmc version/nmc firmware combo?)**
apc-p15-tool done`


is this now a LetsEncrypt Certificate problem?

cause my Card is NMC2 with 7.1.6 latest on it as shown in the previous comment.

**Comment by gregtwallace** [comment]
You're probably using a private key that isn't supported by NMC2. This isn't specific to LE or any other provider. The README lists compatible key types.
