### ISSUE TITLE
install: failed to connect to host (ssh: handshake failed: apcssh: server returned wrong fingerprint

### ISSUE THREAD

**Issue by BrianInAz** [gregtwallace/apc-p15-tool#9]
Trying to install self-signed certificate to my APC unit... getting an error about the server returning the wrong fingerprint:

PS C:\Users\B\Downloads\apc-p15-tool_windows_amd64> .\apc-p15-install.exe --keyfile "C:\Users\B\OneDrive\Desktop\APC\APC.key" --certfile "C:\Users\B\OneDrive\Desktop\APC\APC.crt" --hostname apc.homelab.bjzy.me --fingerprint 8E4D4D1B572B9D944EBC08EBDA5F395D1A53BC92 --username apc --password apc --insecurecipher
apc-p15-tool v1.1.0
install: making apc p15 file(s) content from pem
install: successfully parsed pem files
install: successfully generated p15 key file content
install: key type is supported by NMC2, generating p15 key+cert file content...
install: apc p15 file(s) data succesfully generated
WARNING: install: insecure ciphers are enabled (--insecurecipher). SSH with an insecure cipher is NOT secure and should NOT be used.
**install: failed to connect to host (ssh: handshake failed: apcssh: server returned wrong fingerprint (b64: 68KQzrtc8RSrmm6Jl7Ki7Sex45Scj6tNW2s7f3qR584 ; hex: ebc290cebb5cf114ab9a6e8997b2a2ed27b1e3949c8fab4d5b6b3b7f7a91e7ce))**
apc-p15-tool done

PS C:\Users\B\Downloads\apc-p15-tool_windows_amd64> ssh -vv apc.homelab.bjzy.me
OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2
debug2: resolving "apc.homelab.bjzy.me" port 22
debug1: Connecting to apc.homelab.bjzy.me [192.168.30.2] port 22.
debug1: Connection established.
debug1: identity file C:\\Users\\B/.ssh/id_rsa type -1
debug1: identity file C:\\Users\\B/.ssh/id_rsa-cert type -1
debug1: identity file C:\\Users\\B/.ssh/id_ecdsa type -1
debug1: identity file C:\\Users\\B/.ssh/id_ecdsa-cert type -1
debug1: identity file C:\\Users\\B/.ssh/id_ecdsa_sk type -1
debug1: identity file C:\\Users\\B/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file C:\\Users\\B/.ssh/id_ed25519 type -1
debug1: identity file C:\\Users\\B/.ssh/id_ed25519-cert type -1
debug1: identity file C:\\Users\\B/.ssh/id_ed25519_sk type -1
debug1: identity file C:\\Users\\B/.ssh/id_ed25519_sk-cert type -1
debug1: identity file C:\\Users\\B/.ssh/id_xmss type -1
debug1: identity file C:\\Users\\B/.ssh/id_xmss-cert type -1
debug1: identity file C:\\Users\\B/.ssh/id_dsa type -1
debug1: identity file C:\\Users\\B/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_9.5
kex_exchange_identification: read: Connection reset
Connection reset by 192.168.30.2 port 22
PS C:\Users\B\Downloads\apc-p15-tool_windows_amd64>

**Comment by gregtwallace** [comment]
The fingerprint you specified doesn't match the server. Failure is the expected behavior.

You specified `8E4D4D1B572B9D944EBC08EBDA5F395D1A53BC92`.
The server's fingerprint (in hex) is `ebc290cebb5cf114ab9a6e8997b2a2ed27b1e3949c8fab4d5b6b3b7f7a91e7ce`.
